name: Keep Streamlit App Alive

# This workflow prevents the Streamlit Community Cloud app from hibernating
# by making regular HTTP requests to keep it active

on:
  schedule:
    # Run every 4 hours (at minutes 0 of hours 0, 4, 8, 12, 16, 20)
    # Cron format: minute hour day month day-of-week
    # 0 */4 * * * means: run at minute 0 of every 4th hour, every day
    - cron: '0 */4 * * *'
  
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Keep Streamlit app alive
      run: |
        # Make an HTTP GET request to the Streamlit app URL
        # This prevents the app from going into hibernation mode
        # Replace YOUR_STREAMLIT_APP_URL with your actual app URL
        curl -f https://cricket-match-data-analysis-and-prediction-using-machine-learn.streamlit.app/ || exit 1
        
    - name: Log success
      run: |
        echo "Successfully pinged Streamlit app at $(date)"
